// vector-integration.test.ts — end-to-end tests with the real embedding model.
// These tests load the actual all-MiniLM-L6-v2 ONNX model (~23MB, cached after first download)
// and verify that vector search augments LIKE results with semantic matches.
// Skip with SKIP_VECTOR_INTEGRATION=1 for fast CI runs.

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { SqliteStore } from '../sqlite-store.js';

const testDir = path.dirname(fileURLToPath(import.meta.url));

describe('Vector search integration', () => {
  // Skip if env var is set (for fast CI runs)
  if (process.env.SKIP_VECTOR_INTEGRATION === '1') {
    it.skip('skipped via SKIP_VECTOR_INTEGRATION=1', () => {});
    return;
  }

  let store: SqliteStore;
  let storePath: string;

  // Use beforeAll (not beforeEach) so the model loads once for all tests.
  // Timeout is generous to allow first-time model download (~23MB).
  beforeAll(async () => {
    storePath = path.join(testDir, `test-vec-integration-${Date.now()}.db`);
    store = new SqliteStore(storePath);
    await store.init();

    // Poll until the embedding model is ready (or timeout after 60s)
    const deadline = Date.now() + 60_000;
    while (store.vectorState.status === 'loading' && Date.now() < deadline) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    if (store.vectorState.status !== 'ready') {
      throw new Error(`Embedding model not ready after 60s: ${store.vectorState.status}`);
    }
  }, 120_000); // 2 minute timeout for beforeAll (model download + load)

  afterAll(async () => {
    await store.close();
    for (const suffix of ['', '-wal', '-shm']) {
      try { await fs.unlink(storePath + suffix); } catch { /* ignore */ }
    }
  });

  it('should find semantically similar entities via vector search', async () => {
    // Create entities with specific observations — no LIKE overlap with query
    await store.createEntities([
      { name: 'dog-entity', entityType: 'animal', observations: ['A loyal canine companion that loves to fetch'] },
      { name: 'cat-entity', entityType: 'animal', observations: ['An independent feline that purrs when happy'] },
      { name: 'car-entity', entityType: 'vehicle', observations: ['A four-wheeled motorized vehicle for transport'] },
    ], undefined);

    // Wait for embeddings to be generated by the sweep
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search with a semantically related query that wouldn't match LIKE
    // ("puppy pet" doesn't appear in any observation text)
    const result = await store.searchNodes('puppy pet', undefined);

    // Vector search should find dog-entity via semantic similarity
    const entityNames = result.entities.map(e => e.name);
    expect(entityNames).toContain('dog-entity');
  });

  it('should deduplicate LIKE + vector results', async () => {
    await store.createEntities([
      { name: 'dedup-test', entityType: 'test', observations: ['This is a deduplication test observation'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search with a term that matches BOTH LIKE (substring) and vector (semantic)
    const result = await store.searchNodes('deduplication test', undefined);

    // Entity should appear exactly once, not duplicated from both paths
    const matches = result.entities.filter(e => e.name === 'dedup-test');
    expect(matches).toHaveLength(1);
  });

  it('should exclude superseded observations from vector results', async () => {
    await store.createEntities([
      { name: 'supersede-vec-test', entityType: 'test', observations: ['The sky is green'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Supersede the observation — old embedding should be deleted by syncEmbedding
    await store.supersedeObservations([
      { entityName: 'supersede-vec-test', oldContent: 'The sky is green', newContent: 'The sky is blue' }
    ]);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search should still find the entity via the new observation
    const result = await store.searchNodes('sky color', undefined);
    const found = result.entities.find(e => e.name === 'supersede-vec-test');

    if (found) {
      // If found, it should only have the active observation
      const activeObs = found.observations.map(o => o.content);
      expect(activeObs).toContain('The sky is blue');
      expect(activeObs).not.toContain('The sky is green');
    }
    // Not finding it at all is also acceptable (LIKE might not match "sky color")
  });

  it('should return similarExisting for semantically similar observations', async () => {
    await store.createEntities([
      { name: 'sim-check-test', entityType: 'test', observations: ['The user prefers dark mode for all applications'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Add a semantically similar observation
    const result = await store.addObservations([
      { entityName: 'sim-check-test', contents: ['Dark theme is the preferred color scheme for apps'] }
    ]);

    // The similarity check should flag the existing observation as similar.
    // This is best-effort — may not fire if embeddings aren't ready fast enough.
    if (result[0].similarExisting && result[0].similarExisting.length > 0) {
      expect(result[0].similarExisting[0].content).toContain('dark mode');
      expect(result[0].similarExisting[0].similarity).toBeGreaterThan(0.85);
    }
    // Not having similarExisting is acceptable (best-effort)
  });

  it('should recover historical match via KNN at as_of after the observation was superseded', async () => {
    // This test pins the vector-search-at-as_of fix: vec_observations rows
    // are NOT deleted on supersession, so KNN can still match the historical
    // embedding when queried with an as_of before the supersedeAt timestamp.
    //
    // Use semantically distinct observations with NO substring overlap with
    // the search query, so the only path that can recover the match is KNN
    // (LIKE will return zero results for the query).
    await store.createEntities([
      { name: 'kepler-historical', entityType: 'astronomy', observations: ['An exoplanet hunter spacecraft launched in 2009'] },
    ], undefined);

    // Wait for embedding sweep to pick up the new observation
    await new Promise(resolve => setTimeout(resolve, 2000));
    const beforeSupersede = new Date().toISOString();
    await new Promise(resolve => setTimeout(resolve, 100));

    // Supersede with a totally unrelated observation. The old vec row must
    // remain in vec_observations so historical KNN still finds it.
    await store.supersedeObservations([
      { entityName: 'kepler-historical', oldContent: 'An exoplanet hunter spacecraft launched in 2009', newContent: 'A 17th century German mathematician' }
    ]);
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Query with a phrase that's semantically close to the OLD content but
    // shares no substring with it — only KNN can recover this match.
    const historical = await store.searchNodes('telescope NASA mission', undefined, undefined, beforeSupersede);
    const found = historical.entities.find(e => e.name === 'kepler-historical');

    // Best-effort: model-quality may vary, but at minimum the historical
    // observation must still be present in the entity's observations list
    // when looked up via openNodes at the same as_of.
    const opened = await store.openNodes(['kepler-historical'], undefined, beforeSupersede);
    const historicalEntity = opened.entities.find(e => e.name === 'kepler-historical');
    expect(historicalEntity).toBeDefined();
    expect(historicalEntity!.observations.map(o => o.content)).toContain('An exoplanet hunter spacecraft launched in 2009');

    // If the model quality is good enough that KNN found it via search, verify
    // the historical observation is what came back (not the new mathematician one).
    if (found) {
      const contents = found.observations.map(o => o.content);
      expect(contents).toContain('An exoplanet hunter spacecraft launched in 2009');
    }
  });

  it('should exclude KNN matches when the parent entity is soft-deleted at as_of', async () => {
    // After soft-delete, the entity row's superseded_at is set. Even if a
    // vec_observations row would otherwise match the KNN query, the JOIN to
    // entities should filter it out via temporalEntFilter at as_of > deletion.
    await store.createEntities([
      { name: 'doomed-entity', entityType: 'test', observations: ['A unique watermark phrase about quantum entanglement experiments'] },
    ], undefined);
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Soft-delete the entity
    await store.deleteEntities(['doomed-entity']);
    await new Promise(resolve => setTimeout(resolve, 100));
    const afterDelete = new Date().toISOString();

    // Search at a time AFTER the soft-delete — entity must not appear
    const result = await store.searchNodes('quantum entanglement experiments', undefined, undefined, afterDelete);
    const found = result.entities.find(e => e.name === 'doomed-entity');
    expect(found).toBeUndefined();
  });

  it('checkDuplicates should find semantically similar existing observations', async () => {
    // Use 'dog-entity' from the first test — its observation "A loyal canine
    // companion that loves to fetch" has already been embedded (2s wait in
    // that test + time elapsed since). Check a semantically similar candidate.
    const result = await store.checkDuplicates([
      { entityName: 'dog-entity', content: 'A faithful dog companion who enjoys playing fetch' },
    ]);

    // Model should be ready (loaded in beforeAll)
    expect(result.modelReady).toBe(true);
    expect(result.results).toHaveLength(1);
    expect(result.results[0].entityName).toBe('dog-entity');
    // The existing observation about a canine companion should match
    expect(result.results[0].matches.length).toBeGreaterThanOrEqual(1);
    expect(result.results[0].matches[0].content).toBe(
      'A loyal canine companion that loves to fetch'
    );
    // Similarity should be high (> 0.80 threshold)
    expect(result.results[0].matches[0].similarity).toBeGreaterThan(0.80);
    // createdAt should be a valid ISO timestamp
    expect(result.results[0].matches[0].createdAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it('checkDuplicates should return empty matches for unrelated content', async () => {
    // Use 'dog-entity' — "The weather in Paris" is unrelated to dogs
    const result = await store.checkDuplicates([
      { entityName: 'dog-entity', content: 'The weather in Paris is beautiful in spring' },
    ]);

    expect(result.modelReady).toBe(true);
    expect(result.results).toHaveLength(1);
    // Unrelated content should not match the canine observation
    expect(result.results[0].matches).toHaveLength(0);
  });
});
