// vector-integration.test.ts — end-to-end tests with the real embedding model.
// These tests load the actual all-MiniLM-L6-v2 ONNX model (~23MB, cached after first download)
// and verify that vector search augments LIKE results with semantic matches.
// Skip with SKIP_VECTOR_INTEGRATION=1 for fast CI runs.

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { SqliteStore } from '../sqlite-store.js';

const testDir = path.dirname(fileURLToPath(import.meta.url));

describe('Vector search integration', () => {
  // Skip if env var is set (for fast CI runs)
  if (process.env.SKIP_VECTOR_INTEGRATION === '1') {
    it.skip('skipped via SKIP_VECTOR_INTEGRATION=1', () => {});
    return;
  }

  let store: SqliteStore;
  let storePath: string;

  // Use beforeAll (not beforeEach) so the model loads once for all tests.
  // Timeout is generous to allow first-time model download (~23MB).
  beforeAll(async () => {
    storePath = path.join(testDir, `test-vec-integration-${Date.now()}.db`);
    store = new SqliteStore(storePath);
    await store.init();

    // Poll until the embedding model is ready (or timeout after 60s)
    const deadline = Date.now() + 60_000;
    while (store.vectorState.status === 'loading' && Date.now() < deadline) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    if (store.vectorState.status !== 'ready') {
      throw new Error(`Embedding model not ready after 60s: ${store.vectorState.status}`);
    }
  }, 120_000); // 2 minute timeout for beforeAll (model download + load)

  afterAll(async () => {
    await store.close();
    for (const suffix of ['', '-wal', '-shm']) {
      try { await fs.unlink(storePath + suffix); } catch { /* ignore */ }
    }
  });

  it('should find semantically similar entities via vector search', async () => {
    // Create entities with specific observations — no LIKE overlap with query
    await store.createEntities([
      { name: 'dog-entity', entityType: 'animal', observations: ['A loyal canine companion that loves to fetch'] },
      { name: 'cat-entity', entityType: 'animal', observations: ['An independent feline that purrs when happy'] },
      { name: 'car-entity', entityType: 'vehicle', observations: ['A four-wheeled motorized vehicle for transport'] },
    ], undefined);

    // Wait for embeddings to be generated by the sweep
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search with a semantically related query that wouldn't match LIKE
    // ("puppy pet" doesn't appear in any observation text)
    const result = await store.searchNodes('puppy pet', undefined);

    // Vector search should find dog-entity via semantic similarity
    const entityNames = result.entities.map(e => e.name);
    expect(entityNames).toContain('dog-entity');
  });

  it('should deduplicate LIKE + vector results', async () => {
    await store.createEntities([
      { name: 'dedup-test', entityType: 'test', observations: ['This is a deduplication test observation'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search with a term that matches BOTH LIKE (substring) and vector (semantic)
    const result = await store.searchNodes('deduplication test', undefined);

    // Entity should appear exactly once, not duplicated from both paths
    const matches = result.entities.filter(e => e.name === 'dedup-test');
    expect(matches).toHaveLength(1);
  });

  it('should exclude superseded observations from vector results', async () => {
    await store.createEntities([
      { name: 'supersede-vec-test', entityType: 'test', observations: ['The sky is green'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Supersede the observation — old embedding should be deleted by syncEmbedding
    await store.supersedeObservations([
      { entityName: 'supersede-vec-test', oldContent: 'The sky is green', newContent: 'The sky is blue' }
    ]);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Search should still find the entity via the new observation
    const result = await store.searchNodes('sky color', undefined);
    const found = result.entities.find(e => e.name === 'supersede-vec-test');

    if (found) {
      // If found, it should only have the active observation
      const activeObs = found.observations.map(o => o.content);
      expect(activeObs).toContain('The sky is blue');
      expect(activeObs).not.toContain('The sky is green');
    }
    // Not finding it at all is also acceptable (LIKE might not match "sky color")
  });

  it('should return similarExisting for semantically similar observations', async () => {
    await store.createEntities([
      { name: 'sim-check-test', entityType: 'test', observations: ['The user prefers dark mode for all applications'] },
    ], undefined);

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Add a semantically similar observation
    const result = await store.addObservations([
      { entityName: 'sim-check-test', contents: ['Dark theme is the preferred color scheme for apps'] }
    ]);

    // The similarity check should flag the existing observation as similar.
    // This is best-effort — may not fire if embeddings aren't ready fast enough.
    if (result[0].similarExisting && result[0].similarExisting.length > 0) {
      expect(result[0].similarExisting[0].content).toContain('dark mode');
      expect(result[0].similarExisting[0].similarity).toBeGreaterThan(0.85);
    }
    // Not having similarExisting is acceptable (best-effort)
  });
});
